# fly.toml app configuration file generated for headlesssharp-young-dust-8497 on 2024-12-09T03:52:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'headlesssharp-young-dust-8497'
primary_region = 'lhr'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
